language: java
jdk: oraclejdk8
script: HEROKU_API_KEY="$HEROKU_API_KEY" mvn clean package
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: "$HEROKU_API_KEY"
  app: medservice
services: mongodb
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V